version: "3.9"

services:
  db:
    image: postgres:16
    container_name: simple_lms_db
    environment:
      POSTGRES_DB: simple_lms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: simple_lms_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db  
      - redis
      - mongodb
      - rabbitmq
  
  redis:
    image: redis:7-alpine

  mongodb:
    image: mongo:7

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  celery-worker:
    build: .
    command: celery -A config worker -l info
    depends_on:
      - rabbitmq
      - redis
  
  celery-beat:
    build: .
    command: celery -A config beat -l info
    depends_on:
      - rabbitmq
      - redis
  
  flower:
    build: .
    command: celery -A config flower --port=5555
    ports:
      - "5555:5555"